server:
   port: ${PORT:7001}
 
eureka: 
   instance: 
      hostname: ${eureka.hostname:127.0.0.1}
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 5
      metadataMap: 
              instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   client: 
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
               defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      healthcheck: 
             enabled: true
 